### ISSUE TITLE
Shared library on Windows

### ISSUE THREAD

**Issue by grimbough** [tatami-inc/beachmat#1]
Are you still interested in letting packages link against a `libbeachmat.dll` rather than `libbeachmat.a` on Windows?  Following Martin's explanation on linking against **zlibbioc** I'm pretty sure I can get this to work for us, so there's a compiled-at-install shared library for other packages to link to.

If that's still the preferred option then I'll submit a pull request in a bit once I've done some more testing.

**Comment by LTLA** [comment]
Yes, a shared library would be stylistically better. Give it a go and let's see how fragile it turns out to be.

**Comment by LTLA** [comment]
Merged into a new `sharedlib` branch in 45f3ba327692493c60c49b9cab68e659af9c25f9.
