### ISSUE TITLE
Support for multi-column extraction

### ISSUE THREAD

**Issue by LTLA** [tatami-inc/beachmat#10]
The idea is to have a single function call that extracts multiple columns (or rows) at once. This could be more efficient for `HDF5Matrix` objects as _(hand-waving starts here)_ the HDF5 library would only need to make a single OS call to retrieve data from disk. It would also be a little bit more convenient for users.

I'm torn about this. It's not a lot of work, but it's useful in only very limited circumstances (and even then I'm not sure). Specifically, it would only really be useful for `HDF5Matrix` objects, as multi-column requests would simply involve multiple calls to the single-column getters for the other object types. It would further only be useful for column-chunked files; we get multiple consecutive columns for free with rectangular chunks (via the chunk cache) and it would be madness to do random access with rectangular chunks.

I'm curious to know how much of a difference there is between multiple `read` calls versus a single `read` call. But if performance for on-disk representations is critical, it seems more appropriate to directly call the HDF5 library, rather than relying on _beachmat_ to optimize for speed (it does so for memory).

Pulling in @drisso as he triggered this particular episode. I note that in the case of mini-batching k-means, it would probably be better to use the block-processing mechanism in R anyway, as he will probably need to realize chunks of a `DelayedArray` with non-trivial delayed operations.

Also pulling in @mikejiang, who probably has some thoughts about HDF5 file access speed.

**Comment by LTLA** [comment]
As expected, testing indicates that a single `read` call is about 2-3 times faster than multiple `read` calls, for non-consecutive column access for a column-chunked layout (see the C++ code [here](https://github.com/LTLA/MatrixEval2017/blob/master/simulations/hdf5_tests/access_test.cpp)).

*Sigh*. I guess a `get_cols` method in _beachmat_ would be the logical progression of a system that provides top-level API methods that are visible for all classes but only benefit specific representations.

**Comment by LTLA** [comment]
Uh. Well, this is embarrassing. Looks like it's the other way around - multiple `read` calls are actually 2-3 faster. This is definitely a result of the `H5File::read` call, based on timings after commenting it out. 

We can make the single `read` go almost as fast as multiple `read`s if consecutive columns are extracted, _and_ the output dataspace is two-dimensional. However, it slows down for non-consecutive columns. My guess is that there's some copying inside the HDF5 library to get values in the right locations for output.

**Comment by mikejiang** [comment]
It's been the same frustration for me. When I try to do something clever which is supposed to more optimized way in theory. But it turned out h5 lib doesn't meet your expectation (probably due to its own limits).

**Comment by mikejiang** [comment]
Theoretically speaking we should expect slightly better speed for single-call compared to multi-calls. But when it comes to non-continuous columns,  hyperslab operations within h5 lib (unexpectedly) adds up more overhead than disk IO itself. You can profile your c code to verify this.

**Comment by LTLA** [comment]
Perhaps we're all doing something stupid - I wonder if there's anyone in the HDF5 team we could talk to?

**Comment by mikejiang** [comment]
You can post the question here https://forum.hdfgroup.org/ to see if someone would give a hand.

**Comment by LTLA** [comment]
@mikejiang Yes, that's probably a good idea. Though I'd want to make sure that this behaviour is happening with the "standard" HDF5 library that we get from a system install before asking.

@drisso The multi-column reader is in #11 but it doesn't do any better than reading columns separately for HDF5. It also requires strictly increasing indices, because it was too much hassle otherwise.

**Comment by drisso** [comment]
Thanks @LTLA !

Unfortunately, I cannot contribute much to the discussion, but I appreciate the effort!

**Comment by LTLA** [comment]
In the meantime, the new `get_rows` and `get_cols` methods will try to minimize the penalty by using an output `H5::DataSpace` that matches - as best as possible - the dimensions of the `H5::Dataset`. It seems that this allows the HDF5 library to skip a copy step where it would otherwise rearrange data.

In the future, and in the absence of me having done something stupid, the `get_cols` method may simply revert back to multiple `get_col` calls. This won't happen for the `get_rows` method, though, because the requested submatrix is always returned as column-major so I would have to rearrange it anyway.

While the original intention (of getting a speed boost from a single call to the OS for `HDF5Matrix` objects) was kind of lost, there are some benefits elsewhere from using the `get_rows` or `get_cols` functions. For example, there is now only a single call to R for multi-row/column access for unknown/delayed matrices, avoiding the overhead of multiple calls to R; and `get_rows` access for in-memory matrices should be much faster than multiple `get_row` calls due to better cache performance. As usual, YMMV so test.
