### ISSUE TITLE
incorrect includes/beachmat on Windows

### ISSUE THREAD

**Issue by mtmorgan** [tatami-inc/beachmat#5]
From http://bioconductor.org/checkResults/3.7/bioc-LATEST/scater/tokay2-install.html it seems like delayed_matrix.h is missing from https://github.com/LTLA/beachmat/blob/master/src/Makevars.win#L9 . Maybe a more robust strategy is to create a Makevars.common that is included in Makevars and Makevars.win, like https://github.com/Bioconductor/Rsamtools/blob/master/src/Makevars.common ?

**Comment by LTLA** [comment]
Done in b134cdcc3f11631399ce566a81a5cc81f2562bb3, thanks @mtmorgan.
