### ISSUE TITLE
Compilation Error when Installing

### ISSUE THREAD

**Issue by ShawnyTan** [tatami-inc/beachmat#9]
Hi,

I got a compilation error when installing beachmat on my institute's cluster:

> install.packages("beachmat_1.2.1.tar.gz")
Installing package into ‘/ifs/scratch/c2b2/ac_lab/xt2171/R/lib64/R/library’
(as ‘lib’ is unspecified)
inferring 'repos = NULL' from 'pkgs'
* installing *source* package ‘beachmat’ ...
** libs
g++ -std=gnu++0x -I"/nfs/apps/R/3.5.1/lib64/R/include" -DNDEBUG  -I"/ifs/scratch/c2b2/ac_lab/xt2171/R/lib64/R/library/Rcpp/include" -I"/ifs/scratch/c2b2/ac_lab/xt2171/R/lib64/R/library/Rhdf5lib/include" -I/usr/local/include   -fpic  -g -O2 -c HDF5_utils.cpp -o HDF5_utils.o
In file included from HDF5_utils.h:5,
                 from HDF5_utils.cpp:1:
utils.h:33: error: expected unqualified-id before ‘using’
make: *** [HDF5_utils.o] Error 1
ERROR: compilation failed for package ‘beachmat’
* removing ‘/ifs/scratch/c2b2/ac_lab/xt2171/R/lib64/R/library/beachmat’
Warning message:
In install.packages("/ifs/scratch/c2b2/ac_lab/xt2171/beachmat_1.2.1.tar.gz") :
  installation of package ‘/ifs/scratch/c2b2/ac_lab/xt2171/beachmat_1.2.1.tar.gz’ had non-zero exit status

And the following is my session Info:
> sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.5 (Final)

Matrix products: default
BLAS: /nfs/apps/R/3.5.1/lib64/R/lib/libRblas.so
LAPACK: /nfs/apps/R/3.5.1/lib64/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1   

You have any idea about this error?
Thanks!

**Comment by LTLA** [comment]
If I had to guess, I would say that it's because your version of GCC doesn't provide full support for the C++11 standard, in particular type aliasing via `using`. GCC versions on academic clusters are notoriously ancient, but it's been 7 years since the standard came out, so expecting proper support isn't unreasonable.

**Comment by ShawnyTan** [comment]
Thank you! Problem solved by gcc/6.1.0
